# Generated by Django 5.2.4 on 2025-07-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_budget_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='month',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='year',
        ),
    ]
